version: "3.2"

services:
  crawler-daily:
    image: energy_api_collector/crawler
    build: ./crawler
    privileged: true
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - CRON_TYPE=daily

  crawler-5:
    image: energy_api_collector/crawler
    build: ./crawler
    privileged: true
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - CRON_TYPE=5

  compromizer:
    image: energy_api_collector/compromizer
    build: ./compromizer
    privileged: true
    restart: unless-stopped
    env_file:
      - stack.env