version: "3.2"

services:
  crawler-daily:
    image: energy_api_collector/crawler
    build: ./crawler
    privileged: true
    restart: always
    environment:
      - NEXTCLOUD_URL=""
      - NEXTCLOUD_USER_NAME=""
      - NEXTCLOUD_PASSWORD=""
      - NEXTCLOUD_BASE_FOLDER="energy_api_collector/data/"
      - CRON_TYPE=daily

  crawler-5:
    image: energy_api_collector/crawler
    build: ./crawler
    privileged: true
    restart: always
    environment:
      - NEXTCLOUD_URL=""
      - NEXTCLOUD_USER_NAME=""
      - NEXTCLOUD_PASSWORD=""
      - NEXTCLOUD_BASE_FOLDER="energy_api_collector/data/"
      - CRON_TYPE=5

  compromizer:
    image: energy_api_collector/compromizer
    build: ./compromizer
    privileged: true
    restart: always
    environment:
      - NEXTCLOUD_URL=""
      - NEXTCLOUD_USER_NAME=""
      - NEXTCLOUD_PASSWORD=""
      - NEXTCLOUD_BASE_FOLDER="energy_api_collector/data/"